## Technology Sector Deep-Dive — Revised Findings

**Revenue growth patterns (2009-2022):**

Absolute revenue:
- AAPL: $42.9B → $394.3B (9.2× multiple)
- GOOG: $23.7B → $282.8B (12× multiple — highest multiple)
- MSFT: $58.4B → $198.3B (3.4× multiple — lowest multiple)

Growth consistency (YoY volatility):
- AAPL: highly variable (-8% to +66%) — product-cycle-driven
- GOOG: remarkably consistent (+10% to +41%, mostly mid-teens/twenties) — 
  the steadiest grower
- MSFT: moderately variable (+3% to +18%) — steady but modest

**Sector tailwind confirmed** for aggregate years: 2011, 2018, 2020, 2021 
show all three growing together. But individual years diverge:
- 2015-2016: AAPL super-cycle (+28%, then -8%), others modest
- 2017: GOOG accelerated (+23%) while AAPL/MSFT plodded (+6% each)
- 2019: AAPL declined (-2%) while GOOG/MSFT grew (+18%, +14%)

**Net Profit Margin patterns — more nuanced than typical framing:**

| Company   | Range     | Character                                                             |
|---        |---        |---                                                                    |
| MSFT      | 13% - 37% | Highest peaks but wide swings (2015, 2018 dips)                       |
| GOOG      | 11% - 30% | Moderately high; 2017 EU antitrust fine dropped margin to 11%         |
| AAPL      | 19% - 27% | Steadiest — hardware business drag but consistent                     |

**Revised conclusion:** The Tech trio confirms sector-level revenue tailwinds 
in most years, but the "MSFT highest, GOOG middle, AAPL lowest" margin story 
is too simple. AAPL is actually the most stable margin performer; MSFT has 
higher peaks but more volatility. Each company reflects distinct business 
model dynamics within a shared sector environment.

In [9]:
tech_revenue = tech_df.pivot(
    index="Year",
    columns="Company",
    values="Revenue"
).round(0)
tech_revenue

Company      AAPL      GOOG      MSFT
Year
2009      42905.0   23651.0   58437.0
2010      65225.0   29321.0   62484.0
2011     108249.0   37905.0   69943.0
2012     156508.0   46039.0   73723.0
2013     170910.0   55519.0   77849.0
2014     182795.0   66001.0   86833.0
2015     233715.0   74989.0   93580.0
2016     215639.0   90272.0   91154.0
2017     229234.0  110855.0   96571.0
2018     265595.0  136819.0  110360.0
2019     260174.0  161857.0  125843.0
2020     274515.0  182527.0  143015.0
2021     365817.0  257637.0  168088.0
2022     394328.0  282836.0  198270.0

In [8]:
# Margin Comparison
tech_margins = tech_df.pivot(
    index="Year",
    columns="Company",
    values="Net Profit Margin"
).round(1)
tech_margins

Company  AAPL  GOOG  MSFT
Year
2009     19.2  27.6  24.9
2010     21.5  29.0  30.0
2011     23.9  25.7  33.1
2012     26.7  23.3  23.0
2013     21.7  22.9  28.1
2014     21.6  21.4  25.4
2015     22.8  21.1  13.0
2016     21.2  21.6  22.5
2017     21.1  11.4  26.4
2018     22.4  22.5  15.0
2019     21.2  21.2  31.2
2020     20.9  22.1  31.0
2021     25.9  29.5  36.5
2022     25.3  21.2  36.7

In [7]:
# Pivot for Side by Side Comparison
tech_yoy = tech_df.pivot(
    index="Year",
    columns="Company",
    values="revenue_yoy_pct"
)
tech_yoy

Company  AAPL  GOOG  MSFT
Year
2009      NaN   NaN   NaN
2010     52.0  24.0   6.9
2011     66.0  29.3  11.9
2012     44.6  21.5   5.4
2013      9.2  20.6   5.6
2014      7.0  18.9  11.5
2015     27.9  13.6   7.8
2016     -7.7  20.4  -2.6
2017      6.3  22.8   5.9
2018     15.9  23.4  14.3
2019     -2.0  18.3  14.0
2020      5.5  12.8  13.6
2021     33.3  41.2  17.5
2022      7.8   9.8  18.0

In [6]:
# Sort explicitly by Company then Year (ascending) before computing pct_change
tech_df = tech_df.sort_values(["Company", "Year"])

# Now pct_change compares each row to the previous year's row
tech_df["revenue_yoy_pct"] = (
    tech_df.groupby("Company")["Revenue"].pct_change() * 100
).round(1)

# Verify - AAPL 2010 should show growth from 2009, not decline
tech_df[["Year", "Company", "Revenue", "revenue_yoy_pct"]].head(20)

    Year Company   Revenue  revenue_yoy_pct
13  2009    AAPL   42905.0              NaN
12  2010    AAPL   65225.0             52.0
11  2011    AAPL  108249.0             66.0
10  2012    AAPL  156508.0             44.6
9   2013    AAPL  170910.0              9.2
8   2014    AAPL  182795.0              7.0
7   2015    AAPL  233715.0             27.9
6   2016    AAPL  215639.0             -7.7
5   2017    AAPL  229234.0              6.3
4   2018    AAPL  265595.0             15.9
3   2019    AAPL  260174.0             -2.0
2   2020    AAPL  274515.0              5.5
1   2021    AAPL  365817.0             33.3
0   2022    AAPL  394328.0              7.8
42  2009    GOOG   23651.0              NaN
41  2010    GOOG   29321.0             24.0
40  2011    GOOG   37905.0             29.3
39  2012    GOOG   46039.0             21.5
38  2013    GOOG   55519.0             20.6
37  2014    GOOG   66001.0             18.9

In [2]:
# Filter to Technology Sector
tech_df = df[df["sector"] == "Technology"].copy()

# Quick check
print(f"Technology sector rows: {len(tech_df)}")
print(f"Companies: {tech_df['Company'].unique()}")
print(f"Year range: {tech_df['Year'].min()} to {tech_df['Year'].max()}")

Technology sector rows: 42
Companies: <StringArray>
['AAPL', 'MSFT', 'GOOG']
Length: 3, dtype: str
Year range: 2009 to 2022

In [1]:
import pandas as pd
from pathlib import Path

SCRIPT_DIR = Path().resolve()
df = pd.read_csv(SCRIPT_DIR / "data" / "Financial Statements.csv")
df.columns = df.columns.str.strip()

sector_map = {
    "IT": "Technology", "LOGI": "Logistics", "FOOD": "Food & Beverage",
    "BANK": "Banking", "ELEC": "Electronics", "FinTech": "FinTech",
    "Finance": "Finance", "Manufacturing": "Manufacturing",
}
df["sector"] = df["Category"].map(sector_map)
df = df[(df["Year"] >= 2009) & (df["Year"] <= 2022)]

print(df.shape)

(159, 24)